server:
  port: 8081

spring:
  application:
    name: sharex-server
  
  datasource:
    url: jdbc:postgresql://localhost:5433/sharex
    username: sharex
    password: sharex123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  
  session:
    store-type: jdbc
    timeout: 30m
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION

logging:
  level:
    com.sharex: DEBUG
    org.springframework.security: DEBUG 