version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sharex-postgres
    environment:
      POSTGRES_DB: sharex
      POSTGRES_USER: sharex
      POSTGRES_PASSWORD: sharex123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sharex -d sharex"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: sharex-server
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sharex
      SPRING_DATASOURCE_USERNAME: sharex
      SPRING_DATASOURCE_PASSWORD: sharex123
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: 